### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by phodal** [unit-mesh/b3#1]
Todos

## Core

- [x] Editor UI
    - [x] Menu Bar. Click in menu bar, show menu.
    - [x] Slash Command. Type `/` to show menu.
    - [x] Bubble Menu. Select text, show menu by condition.
    - [ ] Notion Style Bubble. #12 
    - [x] Quick Insert. Type `Command` + `/` or `Ctrl` + `/` to show menu.
- [ ] Change/Diff UI
    - [ ] Diff algorithm
    - [x] Change accept/reject
    - [ ] Libs spike
        - Tiptap: [track-change-extension](https://github.com/chenyuncai/tiptap-track-change-extension)
        - ProseMirror Change: [Changeset](https://github.com/ProseMirror/prosemirror-changeset)
        - [@remirror/extension-diff](https://github.com/remirror/remirror/tree/main/packages/remirror__extension-diff)
- [ ] Localstorage, refs: [vector-storage](https://github.com/nitaiaharoni1/vector-storage)
    - [ ] [Dexie.js](https://github.com/dexie/Dexie.js) IndexedDB ?
- [ ] LLM Connection #3 
    - [ ] Abstract LLM API
    - [x] OpenAI
    - [x] 文心一言 #8 
    - [x] 通义千问 #17  
    - [x] MiniMax #21
    - [x] Imagine Art #21   
    - [ ] Others ?
- [ ] Customize prompt
    - [ ] Pre-Define Context
    - [x] Variable: `$beforeCursor`, `$afterCursor`, `$selection`, `$similarChunk`, `$relatedChunk` #2 
    - [ ] Condition in Prompt #4 
- [ ] Sentence completion

## Intelli Plugin

- [ ] More plugins for Intelli: [https://github.com/ueberdosis/tiptap/issues/819](https://github.com/ueberdosis/tiptap/issues/819)
    - [ ] Sidebar Intellij [Microsoft 365](https://techcommunity.microsoft.com/t5/microsoft-365-blog/introducing-new-ai-enhancements-in-microsoft-365-new-features/ba-p/3643499)

## Web

- [x] Migrate Javascript to Typescript  #5 
- [x] Monorepo for 3b #16
    - [x] Editor package wrapper #19
    - [x] Storybook
- [ ] Wrapper for [EdgeInfer](https://github.com/unit-mesh/edge-infer)
    - WASM version 

## Desktop Version

- [x] Desktop Version
    - [x] [Tauri](https://github.com/tauri-apps/tauri) wrapper  [a7ca27f](https://github.com/unit-mesh/b3/commit/a7ca27fed20eec803f9176d7dca029a279250626)
- [ ] LLM Models Bundle
- [ ] GitHub Action for Auto Release
- [ ] Wrapper for [EdgeInfer](https://github.com/unit-mesh/edge-infer)

## Local LLM

- [ ] Local LLM Spike
    - [ ] Correction text, [MacBERT](https://github.com/ymcui/MacBERT) 
        - [ ] [shibing624/macbert4csc-base-chinese](https://huggingface.co/shibing624/macbert4csc-base-chinese) 
    - [ ] Grammarly
    - [ ] Text Prediction
        - [GPT2-Chinese](https://github.com/Morizeyao/GPT2-Chinese)
        - [uer/gpt2-distil-chinese-cluecorpussmall](https://huggingface.co/uer/gpt2-distil-chinese-cluecorpussmall)
    - [x] Similarity / Sentence Transformer
        -  [x] [sentence-transformers/all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2)
- [ ] Content search
    - [ ] Similar chunk in browser. #11 
    - [ ] Search Engine #13 
    - [ ] Code search

## Code Gen

- [ ] DSL for units
    - [ ] Backend
    - [ ] Frontend
    - [ ] Test code
    - [ ] Test cases
- [ ] Online Runtime
    - [ ] Frontend with [Unit Runtime](https://github.com/unit-mesh/unit-runtime)
